service:
  name: aws-nodejs-ecma-script

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  first:
    handler: first.hello
    events:
      - http:
          method: get
          path: first
  second:
    handler: second.hello
    events:
      - http:
          method: get
          path: second
