service:
  name: pets-aws-service

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  createPet:
    handler: handler.create
    events:
      - http:
          method: POST
          path: create
  showPet:
    handler: handler.show
    events:
      - http:
          path: pets/{petId}
          method: GET
  listPets:
    handler: handler.list
    events:
      - http:
          path: pets
          method: GET
